export const ADD_CARD = 'ADD_CARD';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
export const HANDLE_CHECK = 'HANDLE_CHECK';
export const REMOVE_CARD = 'REMOVE_CARD';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECIVE_LOGIN = 'RECIVE_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REQUEST_LOGIN_FB = "REQUEST_LOGIN_FB";
export const RECIVE_LOGIN_FB = "RECIVE_LOGIN_FB";